name: Build And Test Application
on: [push, workflow_dispatch]
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Get code
              uses: actions/checkout@v4.1.1
            - name: Setup NodeJS
              uses: actions/Setup-node@v4
              with:
                node-version: 16
            - name: Install dependencies
              run: npm install
            - name: Build and test application
              run: npm run test:e2e
